### ISSUE TITLE
Using the plugin gives error 10 and 5

### ISSUE THREAD

**Issue by AntiAsko** [pbakondy/ng-cordova-settings#1]
While the pluging works perfectly in browser when trying in at Android emulator it gives error code 10. Moreover when I tried it in an android device it gives me error 5

**Comment by pbakondy** [comment]
I tested again in Android emulator and in Android device too. It works for me.

Please check:
- org.apache.cordova.file is installed
- ngCordova version

For ngCordova: 
If you installed this package with bower, it should be ok.
There is a wrong version number in the header of latest ng-cordova.js and ng-cordova.min.js .
You can make sure of having the latest version if you find the following method in ng-cordova.js :
  writeExistingFile: function (path, fileName, text)

**Comment by AntiAsko** [comment]
Probably I am doing something wrong. I have latest ngCordova version installed and the file plugin. I will have to double check that my code is all right.

**Comment by AntiAsko** [comment]
The plugin workes perfectly. It was my mistake from the begining
